sonar.projectKey=shademounir_gestion-ressources-materielles
sonar.organization=gestion-ressources-materielles
sonar.projectName=Gestion des Ressources Materielles
sonar.host.url=https://sonarcloud.io

sonar.sources=backend/src,frontend/src
sonar.tests=backend/src,frontend/src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts,**/*.test.tsx

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/build/**,**/.next/**,**/.vite/**,**/tmp/**,**/temp/**,backend/prisma/migrations/**
sonar.coverage.exclusions=**/*.spec.ts,**/*.test.ts,**/*.test.tsx,**/*.config.ts,**/*.config.mjs,backend/src/main.ts

sonar.typescript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
sonar.sourceEncoding=UTF-8
