export enum UserRole {
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  USER = 'USER',
  RESOURCE_MANAGER = 'RESOURCE_MANAGER',
  DEPARTMENT_HEAD = 'DEPARTMENT_HEAD',
  TEACHER = 'TEACHER',
  SUPPLIER = 'SUPPLIER',
  MAINTENANCE_TECHNICIAN = 'MAINTENANCE_TECHNICIAN',
}
